insert into member(name, city, street, zipcode) values('nick','Seoul','Songi-ro','05705');
insert into member(name, city, street, zipcode) values('duck','Seoul','S-ro','12345');
insert into member(name, city, street, zipcode) values('luke','Seoul','o-ro','23456');
insert into member(name, city, street, zipcode) values('learnerduck','Seoul','n-ro','34567');
insert into member(name, city, street, zipcode) values('광일','서울','g-ro','45678');
insert into member(name, city, street, zipcode) values('덕수','대구','i-ro','56789');
insert into member(name, city, street, zipcode) values('태식','대전','So-ro','13579');
insert into member(name, city, street, zipcode) values('재주','부산','on-ro','54321');
insert into member(name, city, street, zipcode) values('지우','제주','ng-ro','65432');
insert into member(name, city, street, zipcode) values('우빈','충주','gi-ro','76543');
insert into member(name, city, street, zipcode) values('광일2','서울','g-ro','45678');
insert into member(name, city, street, zipcode) values('덕수2','대구','i-ro','56789');
insert into member(name, city, street, zipcode) values('태식2','대전','So-ro','13579');
insert into member(name, city, street, zipcode) values('재주2','부산','on-ro','54321');
insert into member(name, city, street, zipcode) values('지우2','제주','ng-ro','65432');
insert into member(name, city, street, zipcode) values('우빈2','충주','gi-ro','76543');
insert into member(name, city, street, zipcode) values('광일3','서울','g-ro','45678');
insert into member(name, city, street, zipcode) values('덕수3','대구','i-ro','56789');
insert into member(name, city, street, zipcode) values('태식3','대전','So-ro','13579');
insert into member(name, city, street, zipcode) values('재주3','부산','on-ro','54321');
insert into member(name, city, street, zipcode) values('지우3','제주','ng-ro','65432');
insert into member(name, city, street, zipcode) values('우빈3','충주','gi-ro','76543');

insert into item(name, price, stock_quantity, author, isbn, dtype) values('toby spring','50000','3','toby','qwert-12345','B');
insert into item(name, price, stock_quantity, author, isbn, dtype) values('toby summer','40000','8','toby','qwert-12345','B');
insert into item(name, price, stock_quantity, author, isbn, dtype) values('toby autumn','30000','2','toby','qwert-12345','B');
insert into item(name, price, stock_quantity, author, isbn, dtype) values('toby winter','20000','1','toby','qwert-12345','B');
insert into item(name, price, stock_quantity, author, isbn, dtype) values('spring','10000','2','toby','qwert-12345','B');
insert into item(name, price, stock_quantity, author, isbn, dtype) values('summer','55000','3','toby','qwert-12345','B');
insert into item(name, price, stock_quantity, author, isbn, dtype) values('autumn','54000','4','toby','qwert-12345','B');
insert into item(name, price, stock_quantity, author, isbn, dtype) values('winter','53000','3','toby','qwert-12345','B');
insert into item(name, price, stock_quantity, author, isbn, dtype) values('spring is coming','52000','7','toby','qwert-12345','B');
insert into item(name, price, stock_quantity, author, isbn, dtype) values('summer is coming','51000','2','toby','qwert-12345','B');
insert into item(name, price, stock_quantity, author, isbn, dtype) values('autumn is coming','56000','3','toby','qwert-12345','B');
insert into item(name, price, stock_quantity, author, isbn, dtype) values('winter is coming','57000','2','toby','qwert-12345','B');
